### ISSUE TITLE
在Listview中使用 设置宽度自动适应父VIew 

### ISSUE THREAD

**Issue by Cornflower1991** [xiaopansky/LinearLineWrapLayout#2]
在LIstview中 设置setAdjustChildWidthWithParent 自动适应宽度。滑动之后自动适应不起作用了。 请问如何修改 谢谢  我设置了tag貌似也不行

**Comment by xiaopansky** [comment]
每次走getView的时候 layout里面的内容是否清空重新添加了？

**Comment by Cornflower1991** [comment]
肯定要清空 不然会重复添加。谢谢  我已经解决了 我在外边套了FrameLayout。然后FrameLayout大小固定。ImageView 在里边match_parent。 我感觉应该加载图片的问题 用的Glide
